export const CONTINUITY_RULES = `CAUSAL CONTINUITY — conditional consistency checks, never a plot template:
APPLICABILITY FIRST: Apply each check ONLY when the author's premise, established story or current scene actually contains the corresponding situation. Skip irrelevant checks silently. The examples below illustrate errors, not story facts or required content. Never introduce shops, missions, reward systems, resource ledgers, villagers, soldiers, rulers, secret items or world crossings to satisfy these checks. Preserve the chosen genre, setting, character goals and narrative voice.
PROPORTIONATE DETAIL: Ordinary plausible object use does not require an acquisition scene; investigate provenance only when access, ownership, scarcity or an explicit catalogue makes it consequential. Check arithmetic only for quantities the story actually specifies, not every meal or possession. Require a causal bridge only when an unexplained return or change would confuse the audience; routine transitions may remain implicit. Do not add statistics, exposition, timestamps, named groups or memory records for absent story elements. Respect established intentional ambiguity, unreliable narration, flashbacks and genre-specific rules; do not flatten them into literal contradictions without evidence.
ITEM PROVENANCE: Track where each usable object comes from, who holds it, whether its category is unlocked and the acquisition event. A defined shop catalogue is closed unless expansion is explicitly established. Never pull an unlisted knife or tool out of that shop for convenience. Do not silently add it to the catalogue during correction. Use an already available object or remove the unsupported action; do not invent prior acquisition. Distinguish village-owned tools from shop products.
INVENTORY ARITHMETIC: For each resource keep starting quantity, unit, evidenced additions, expenditures, losses and remaining quantity. Remaining = starting + additions - consumption - losses. Distinguish resource portions consumed from bowls/people served: ten portions shared among thirteen people still consume ten, not thirteen. Thirty portions minus ten leaves twenty unless a separate three-portion use is established. Never invent consumption to justify a displayed balance. Do not equate one bag with one portion without an established conversion; keep unknown bag contents unknown. Include non-food uses such as bait and carry those deductions into later balances. Correct the smallest set of numeric statements consistent with explicit transactions.
RETURNING GROUPS: Track departures, destination, elapsed time and the cause of any return. A retreating force must not silently reappear at another site. Establish a plausible brief causal transition and sufficient travel opportunity when supported by the story, or remove an unsupported return. Treat a missing transition as a clarity issue, not automatically a contradiction. Do not invent a new spy, order, route or hidden operation just to explain it.
ENDING IDENTITY AND CHANGE: Reuse the established name/title for an existing character, especially an offscreen ruler, instead of introducing an ambiguous new label such as a young lord at the ending. Do not invent age or identity. A reversal from monopoly to sharing needs an evidenced decision, pressure, consequence or attributed report in narrative order. Do not turn an assumption into a completed reform. If no support exists, narrow the ending to the outcome actually shown rather than assert a sudden change of heart. No extra subplot is required.
ADDITIONAL MEMORY: Record catalogue restrictions as core rules, item acquisition/ownership as object updates, resource quantities with explicit units and transaction reasons as core facts while relevant, departed groups with last location/destination as state, and identity aliases or evidenced decisions with stable character IDs. These checks run within the existing single correction/memory pass; no extra audit call. Source IDs locate evidence but do not prove arithmetic, access rights or motivation.
TIME: Track the current day/time, each timed obligation's starting point, required duration and evidenced elapsed time. A chapter boundary, dawn or a character's earlier three-day fast does not prove three days since a new mission began. Never mark a timed task complete before its own interval has elapsed. Keep it pending when time is unknown; do not invent an offscreen time jump just to justify a reward.
PREREQUISITES: Track each mission's separate conditions, their supporting events and when they became true. All prerequisites must precede completion, which must precede granting/using its reward. Never use the reward itself as evidence for its own unlock: clean water -> completion -> purifier -> first clean water is circular. Planning water, owning a locked purifier or being told a condition is satisfied is not proof of producing safe water. Distinguish planned, available, used and verified. Do not change the original mission conditions to hide an error.
COUNTS: Keep named membership and scope for each group: villagers, companions, protagonist, beneficiaries and mission targets may differ. Compute totals from disjoint groups, not duplicated names. Ten villagers plus two additional companions means twelve beneficiaries, but a ten-villager mission can still target ten if explicitly scoped. Do not count the protagonist implicitly or silently change ten targets to twelve. Rations, survivors, arrivals and departures must use the appropriate roster at that moment.
KNOWLEDGE: Separate narrator/player knowledge, private system information and each character's knowledge. Before a character acts on a secret, require an earlier witnessed event, audible conversation, identified report or evidenced deduction available to THAT character. Possibility of a spy is not an established source. Do not let enemies name a newly obtained secret item merely because the narrator mentioned it. Keep suspicions distinct from facts.
LOCAL CORRECTION: In the existing single correction pass, trace these four chains before returning edits and memory. Correct the smallest coherent set of dependent lines, including a false completion AND any reward use that depends on it; changing only one announcement is insufficient. Preserve established facts and author constraints. Prefer pending progress or removing unsupported certainty over inventing days, spies, rescue resources or retroactive exceptions. Do not rewrite correct scenes. Evidence quotes must come from the corrected prose; a false system announcement cannot validate its own prerequisites.
MEMORY: Use existing keyed updates, no new transport envelope. Store active deadlines/mission conditions as kind=requirement and importance=core, elapsed time and group rosters as core facts, and secret knowledge with its holders and acquisition source as core facts while relevant. Reuse stable IDs. Record elapsed/remaining time and unresolved prerequisites explicitly; never mark them resolved from an unsupported announcement. Keep separate group IDs for targets and beneficiaries. Record unknown time/source as unknown. Carry changed facts through the global memory and retain source evidence.`
